#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="\$0"
# Need this for relative symlinks.
while [ -h "\$PRG" ]; do
  ls="$(ls -ld "\$PRG")"
  link="$(expr "\$ls" : '.*-> \\(.*\\)$')"
  if expr "\$link" : '/.*' >/dev/null; then
    PRG="\$link"
  else
    PRG="$(dirname "\$PRG")/\$link"
  fi
 done

SAVED="$(pwd)"
cd "$(dirname "\$PRG")/" >/dev/null
APP_HOME="$(pwd -P)"
cd "\$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "\$0")

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
  echo "\$*"
}

_die () {
  echo
  echo "\$*"
  echo
  exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
Darwin=false
NONSTOP=false
case "$(uname)" in
  CYGWIN*) cygwin=true ;;
  Darwin*) Darwin=true ;;
  MINGW*) msys=true ;;
  MSYS*) msys=true ;;
  NONSTOP*) NONSTOP=true ;;
 esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
  if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
    # IBM's JDK on AIX uses strange locations for the executables
    JAVACMD="\$JAVA_HOME/jre/sh/java"
  else
    JAVACMD="\$JAVA_HOME/bin/java"
  fi
  if [ ! -x "\$JAVACMD" ] ; then
    _die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the location of your Java installation."
  fi
else
  JAVACMD="java"
  which java >/dev/null 2>&1 || _die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "\$cygwin" = "false" -a "\$Darwin" = "false" -a "\$NONSTOP" = "false" ]; then
  MAX_FD_LIMIT=$(ulimit -H -n)
  if [ "\$?" -eq 0 ]; then
    if [ "\$MAX_FD" = "maximum" -o "\$MAX_FD" = "max" ]; then
      MAX_FD="\$MAX_FD_LIMIT"
    fi
    ulimit -n "\$MAX_FD"  >/dev/null 2>&1 || warn "Could not set maximum file descriptor limit: \$MAX_FD"
  else
    warn "Could not query maximum file descriptor limit: \$MAX_FD_LIMIT"
  fi
fi

# For Darwin, add options to specify how the application appears in the dock
if [ "\$Darwin" = "true" ]; then
  GRADLE_OPTS="\$GRADLE_OPTS\n-Dapple.awt.UIElement=true"
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "\$cygwin" = "true" -o "\$msys" = "true" ] ; then
  APP_HOME=$(cygpath --path --mixed "\$APP_HOME")
  CLASSPATH=$(cygpath --path --mixed "\$CLASSPATH")
  JAVACMD=$(cygpath --unix "\$JAVACMD")

  # We build the pattern for arguments to be converted via cygpath
  ROOTDIRSRAW=$(find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null)
  SEP=""
  for dir in \$ROOTDIRSRAW ; do
    ROOTDIRS="\$ROOTDIRS\$SEP\$dir"
    SEP="|"
  done
  OURCYGPATTERN="(^|;)\(\$ROOTDIRS\)/*"
  # Add a user-defined pattern to the cygpath arguments
  if [ "\$GRADLE_CYGPATTERN" != "" ] ; then
    OURCYGPATTERN="\$OURCYGPATTERN|\(\$GRADLE_CYGPATTERN\)"
  fi
  # Now convert the arguments - kludge to limit ourselves to /bin/sh
  i=0
  for arg in "\$@" ; do
    CHECK=$(echo "\$arg" | egrep -c "\$OURCYGPATTERN" -)
    CHECK2=$(echo "\$arg" | egrep -c "^-[^=]*@" -)
    if [ "\$CHECK" != "0" ] && [ "\$CHECK2" = "0" ] ; then
      eval "arg\$i=\"\$(cygpath --path --ignore --mixed \"\$arg\")\""
    else
      eval "arg\$i=\"\$arg\""
    fi
    i=$(expr \$i + 1)
  done
  case \$i in
    0) set -- ;;
    1) set -- "\$arg0" ;;
    2) set -- "\$arg0" "\$arg1" ;;
    3) set -- "\$arg0" "\$arg1" "\$arg2" ;;
    4) set -- "\$arg0" "\$arg1" "\$arg2" "\$arg3" ;;
    5) set -- "\$arg0" "\$arg1" "\$arg2" "\$arg3" "\$arg4" ;;
    6) set -- "\$arg0" "\$arg1" "\$arg2" "\$arg3" "\$arg4" "\$arg5" ;;
    7) set -- "\$arg0" "\$arg1" "\$arg2" "\$arg3" "\$arg4" "\$arg5" "\$arg6" ;;
    8) set -- "\$arg0" "\$arg1" "\$arg2" "\$arg3" "\$arg4" "\$arg5" "\$arg6" "\$arg7" ;;
    *) set -- "\$arg0" "\$arg1" "\$arg2" "\$arg3" "\$arg4" "\$arg5" "\$arg6" "\$arg7" "\$arg8" "\${@:9}" ;;
  esac
fi

# Escape application args
save () {
  for i in "\$@" ; do printf %s\\n "\$i" | sed "s/'/'\\''/g;1s/^/'/;
\$s/\$/'/" ; done
  printf " "
}
APP_ARGS=$(save "\$@")

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- "\$DEFAULT_JVM_OPTS" "\$JAVA_OPTS" "\$GRADLE_OPTS" "-Dorg.gradle.appname=\$APP_BASE_NAME" -classpath "\$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "\$APP_ARGS"

exec "\$JAVACMD" "\$@"
